#!/bin/bash

####################
# casme2
# MEGC2022
# positive
python demo.py  --config config/casme2-256.yaml --source_image ../../../hdd/Data/Facial_Micro-Expression/megc2022-synthesis/target_template_face/Template_Female_Asian_crop.png  --driving_video ../../../hdd/Data/Facial_Micro-Expression/megc2022-synthesis/source_samples/casme2_challenge_256_png/Positive_EP01_01f.mp4 --source_image_edge ../../../hdd/Data/Facial_Micro-Expression/megc2022-synthesis/target_template_face/Template_Female_Asian_crop_edge.jpg  --driving_video_edge ../../../hdd/Data/Facial_Micro-Expression/megc2022-synthesis/source_samples/casme2_challenge_256_png_edge/Positive_EP01_01f.mp4 --result_video checkpoints_casme2/Positive_EP01_01f_Female_Asian.mp4   --checkpoint checkpoints_casme2/00000149-checkpoint.pth.tar --relative --adapt_scale
python demo.py  --config config/casme2-256.yaml --source_image ../../../hdd/Data/Facial_Micro-Expression/megc2022-synthesis/target_template_face/Template_Female_Europe_crop.png --driving_video ../../../hdd/Data/Facial_Micro-Expression/megc2022-synthesis/source_samples/casme2_challenge_256_png/Positive_EP01_01f.mp4 --source_image_edge ../../../hdd/Data/Facial_Micro-Expression/megc2022-synthesis/target_template_face/Template_Female_Europe_crop_edge.jpg --driving_video_edge ../../../hdd/Data/Facial_Micro-Expression/megc2022-synthesis/source_samples/casme2_challenge_256_png_edge/Positive_EP01_01f.mp4 --result_video checkpoints_casme2/Positive_EP01_01f_Female_Europe.mp4  --checkpoint checkpoints_casme2/00000149-checkpoint.pth.tar --relative --adapt_scale
python demo.py  --config config/casme2-256.yaml --source_image ../../../hdd/Data/Facial_Micro-Expression/megc2022-synthesis/target_template_face/Template_Male_Asian_crop.png    --driving_video ../../../hdd/Data/Facial_Micro-Expression/megc2022-synthesis/source_samples/casme2_challenge_256_png/Positive_EP01_01f.mp4 --source_image_edge ../../../hdd/Data/Facial_Micro-Expression/megc2022-synthesis/target_template_face/Template_Male_Asian_crop_edge.jpg    --driving_video_edge ../../../hdd/Data/Facial_Micro-Expression/megc2022-synthesis/source_samples/casme2_challenge_256_png_edge/Positive_EP01_01f.mp4 --result_video checkpoints_casme2/Positive_EP01_01f_Male_Asian.mp4     --checkpoint checkpoints_casme2/00000149-checkpoint.pth.tar --relative --adapt_scale
python demo.py  --config config/casme2-256.yaml --source_image ../../../hdd/Data/Facial_Micro-Expression/megc2022-synthesis/target_template_face/Template_Male_Europe_crop.png   --driving_video ../../../hdd/Data/Facial_Micro-Expression/megc2022-synthesis/source_samples/casme2_challenge_256_png/Positive_EP01_01f.mp4 --source_image_edge ../../../hdd/Data/Facial_Micro-Expression/megc2022-synthesis/target_template_face/Template_Male_Europe_crop_edge.jpg   --driving_video_edge ../../../hdd/Data/Facial_Micro-Expression/megc2022-synthesis/source_samples/casme2_challenge_256_png_edge/Positive_EP01_01f.mp4 --result_video checkpoints_casme2/Positive_EP01_01f_Male_Europe.mp4    --checkpoint checkpoints_casme2/00000149-checkpoint.pth.tar --relative --adapt_scale
# negative
python demo.py  --config config/casme2-256.yaml --source_image ../../../hdd/Data/Facial_Micro-Expression/megc2022-synthesis/target_template_face/Template_Female_Asian_crop.png   --driving_video ../../../hdd/Data/Facial_Micro-Expression/megc2022-synthesis/source_samples/casme2_challenge_256_png/Negative_EP19_06f.mp4 --source_image_edge ../../../hdd/Data/Facial_Micro-Expression/megc2022-synthesis/target_template_face/Template_Female_Europe_crop_edge.jpg  --driving_video_edge ../../../hdd/Data/Facial_Micro-Expression/megc2022-synthesis/source_samples/casme2_challenge_256_png_edge/Negative_EP19_06f.mp4 --result_video checkpoints_casme2/Negative_EP19_06f_Female_Asian.mp4  --checkpoint checkpoints_casme2/00000149-checkpoint.pth.tar --relative --adapt_scale
python demo.py  --config config/casme2-256.yaml --source_image ../../../hdd/Data/Facial_Micro-Expression/megc2022-synthesis/target_template_face/Template_Female_Europe_crop.png  --driving_video ../../../hdd/Data/Facial_Micro-Expression/megc2022-synthesis/source_samples/casme2_challenge_256_png/Negative_EP19_06f.mp4 --source_image_edge ../../../hdd/Data/Facial_Micro-Expression/megc2022-synthesis/target_template_face/Template_Female_Europe_crop_edge.jpg  --driving_video_edge ../../../hdd/Data/Facial_Micro-Expression/megc2022-synthesis/source_samples/casme2_challenge_256_png_edge/Negative_EP19_06f.mp4 --result_video checkpoints_casme2/Negative_EP19_06f_Female_Europe.mp4 --checkpoint checkpoints_casme2/00000149-checkpoint.pth.tar --relative --adapt_scale
python demo.py  --config config/casme2-256.yaml --source_image ../../../hdd/Data/Facial_Micro-Expression/megc2022-synthesis/target_template_face/Template_Male_Asian_crop.png     --driving_video ../../../hdd/Data/Facial_Micro-Expression/megc2022-synthesis/source_samples/casme2_challenge_256_png/Negative_EP19_06f.mp4 --source_image_edge ../../../hdd/Data/Facial_Micro-Expression/megc2022-synthesis/target_template_face/Template_Male_Asian_crop_edge.jpg     --driving_video_edge ../../../hdd/Data/Facial_Micro-Expression/megc2022-synthesis/source_samples/casme2_challenge_256_png_edge/Negative_EP19_06f.mp4 --result_video checkpoints_casme2/Negative_EP19_06f_Male_Asian.mp4    --checkpoint checkpoints_casme2/00000149-checkpoint.pth.tar --relative --adapt_scale
python demo.py  --config config/casme2-256.yaml --source_image ../../../hdd/Data/Facial_Micro-Expression/megc2022-synthesis/target_template_face/Template_Male_Europe_crop.png    --driving_video ../../../hdd/Data/Facial_Micro-Expression/megc2022-synthesis/source_samples/casme2_challenge_256_png/Negative_EP19_06f.mp4 --source_image_edge ../../../hdd/Data/Facial_Micro-Expression/megc2022-synthesis/target_template_face/Template_Male_Europe_crop_edge.jpg    --driving_video_edge ../../../hdd/Data/Facial_Micro-Expression/megc2022-synthesis/source_samples/casme2_challenge_256_png_edge/Negative_EP19_06f.mp4 --result_video checkpoints_casme2/Negative_EP19_06f_Male_Europe.mp4   --checkpoint checkpoints_casme2/00000149-checkpoint.pth.tar --relative --adapt_scale
# surprise
python demo.py  --config config/casme2-256.yaml --source_image ../../../hdd/Data/Facial_Micro-Expression/megc2022-synthesis/target_template_face/Template_Female_Asian_crop.png   --driving_video ../../../hdd/Data/Facial_Micro-Expression/megc2022-synthesis/source_samples/casme2_challenge_256_png/Surprise_EP01_13.mp4 --source_image_edge ../../../hdd/Data/Facial_Micro-Expression/megc2022-synthesis/target_template_face/Template_Female_Europe_crop_edge.jpg  --driving_video_edge ../../../hdd/Data/Facial_Micro-Expression/megc2022-synthesis/source_samples/casme2_challenge_256_png_edge/Surprise_EP01_13.mp4 --result_video checkpoints_casme2/Surprise_EP01_13_Female_Asian.mp4   --checkpoint checkpoints_casme2/00000149-checkpoint.pth.tar --relative --adapt_scale
python demo.py  --config config/casme2-256.yaml --source_image ../../../hdd/Data/Facial_Micro-Expression/megc2022-synthesis/target_template_face/Template_Female_Europe_crop.png  --driving_video ../../../hdd/Data/Facial_Micro-Expression/megc2022-synthesis/source_samples/casme2_challenge_256_png/Surprise_EP01_13.mp4 --source_image_edge ../../../hdd/Data/Facial_Micro-Expression/megc2022-synthesis/target_template_face/Template_Female_Europe_crop_edge.jpg  --driving_video_edge ../../../hdd/Data/Facial_Micro-Expression/megc2022-synthesis/source_samples/casme2_challenge_256_png_edge/Surprise_EP01_13.mp4 --result_video checkpoints_casme2/Surprise_EP01_13_Female_Europe.mp4  --checkpoint checkpoints_casme2/00000149-checkpoint.pth.tar --relative --adapt_scale
python demo.py  --config config/casme2-256.yaml --source_image ../../../hdd/Data/Facial_Micro-Expression/megc2022-synthesis/target_template_face/Template_Male_Asian_crop.png     --driving_video ../../../hdd/Data/Facial_Micro-Expression/megc2022-synthesis/source_samples/casme2_challenge_256_png/Surprise_EP01_13.mp4 --source_image_edge ../../../hdd/Data/Facial_Micro-Expression/megc2022-synthesis/target_template_face/Template_Male_Asian_crop_edge.jpg     --driving_video_edge ../../../hdd/Data/Facial_Micro-Expression/megc2022-synthesis/source_samples/casme2_challenge_256_png_edge/Surprise_EP01_13.mp4 --result_video checkpoints_casme2/Surprise_EP01_13_Male_Asian.mp4     --checkpoint checkpoints_casme2/00000149-checkpoint.pth.tar --relative --adapt_scale
python demo.py  --config config/casme2-256.yaml --source_image ../../../hdd/Data/Facial_Micro-Expression/megc2022-synthesis/target_template_face/Template_Male_Europe_crop.png    --driving_video ../../../hdd/Data/Facial_Micro-Expression/megc2022-synthesis/source_samples/casme2_challenge_256_png/Surprise_EP01_13.mp4 --source_image_edge ../../../hdd/Data/Facial_Micro-Expression/megc2022-synthesis/target_template_face/Template_Male_Europe_crop_edge.jpg    --driving_video_edge ../../../hdd/Data/Facial_Micro-Expression/megc2022-synthesis/source_samples/casme2_challenge_256_png_edge/Surprise_EP01_13.mp4 --result_video checkpoints_casme2/Surprise_EP01_13_Male_Europe.mp4    --checkpoint checkpoints_casme2/00000149-checkpoint.pth.tar --relative --adapt_scale




####################
# smic
# MEGC2022
# positive
python demo.py  --config config/smic-256.yaml --source_image ../../../hdd/Data/Facial_Micro-Expression/megc2022-synthesis/target_template_face/Template_Female_Asian_crop.png  --driving_video ../../../hdd/Data/Facial_Micro-Expression/megc2022-synthesis/source_samples/Smic_challenge_256_png/Positive_s3_po_05.mp4 --source_image_edge ../../../hdd/Data/Facial_Micro-Expression/megc2022-synthesis/target_template_face/Template_Female_Asian_crop_edge.jpg  --driving_video_edge ../../../hdd/Data/Facial_Micro-Expression/megc2022-synthesis/source_samples/Smic_challenge_256_png_edge/Positive_s3_po_05.mp4 --result_video checkpoints_smic/Positive_s3_po_05_Female_Asian.mp4   --checkpoint checkpoints_smic/00000149-checkpoint.pth.tar --relative --adapt_scale
python demo.py  --config config/smic-256.yaml --source_image ../../../hdd/Data/Facial_Micro-Expression/megc2022-synthesis/target_template_face/Template_Female_Europe_crop.png --driving_video ../../../hdd/Data/Facial_Micro-Expression/megc2022-synthesis/source_samples/Smic_challenge_256_png/Positive_s3_po_05.mp4 --source_image_edge ../../../hdd/Data/Facial_Micro-Expression/megc2022-synthesis/target_template_face/Template_Female_Europe_crop_edge.jpg --driving_video_edge ../../../hdd/Data/Facial_Micro-Expression/megc2022-synthesis/source_samples/Smic_challenge_256_png_edge/Positive_s3_po_05.mp4 --result_video checkpoints_smic/Positive_s3_po_05_Female_Europe.mp4  --checkpoint checkpoints_smic/00000139-checkpoint.pth.tar --relative --adapt_scale
python demo.py  --config config/smic-256.yaml --source_image ../../../hdd/Data/Facial_Micro-Expression/megc2022-synthesis/target_template_face/Template_Male_Asian_crop.png    --driving_video ../../../hdd/Data/Facial_Micro-Expression/megc2022-synthesis/source_samples/Smic_challenge_256_png/Positive_s3_po_05.mp4 --source_image_edge ../../../hdd/Data/Facial_Micro-Expression/megc2022-synthesis/target_template_face/Template_Male_Asian_crop_edge.jpg    --driving_video_edge ../../../hdd/Data/Facial_Micro-Expression/megc2022-synthesis/source_samples/Smic_challenge_256_png_edge/Positive_s3_po_05.mp4 --result_video checkpoints_smic/Positive_s3_po_05_Male_Asian.mp4     --checkpoint checkpoints_smic/00000149-checkpoint.pth.tar --relative --adapt_scale
python demo.py  --config config/smic-256.yaml --source_image ../../../hdd/Data/Facial_Micro-Expression/megc2022-synthesis/target_template_face/Template_Male_Europe_crop.png   --driving_video ../../../hdd/Data/Facial_Micro-Expression/megc2022-synthesis/source_samples/Smic_challenge_256_png/Positive_s3_po_05.mp4 --source_image_edge ../../../hdd/Data/Facial_Micro-Expression/megc2022-synthesis/target_template_face/Template_Male_Europe_crop_edge.jpg   --driving_video_edge ../../../hdd/Data/Facial_Micro-Expression/megc2022-synthesis/source_samples/Smic_challenge_256_png_edge/Positive_s3_po_05.mp4 --result_video checkpoints_smic/Positive_s3_po_05_Male_Europe.mp4    --checkpoint checkpoints_smic/00000149-checkpoint.pth.tar --relative --adapt_scale
# negative
python demo.py  --config config/smic-256.yaml --source_image ../../../hdd/Data/Facial_Micro-Expression/megc2022-synthesis/target_template_face/Template_Female_Asian_crop.png   --driving_video ../../../hdd/Data/Facial_Micro-Expression/megc2022-synthesis/source_samples/Smic_challenge_256_png/Negative_s11_ne_02.mp4 --source_image_edge ../../../hdd/Data/Facial_Micro-Expression/megc2022-synthesis/target_template_face/Template_Female_Europe_crop_edge.jpg  --driving_video_edge ../../../hdd/Data/Facial_Micro-Expression/megc2022-synthesis/source_samples/Smic_challenge_256_png_edge/Negative_s11_ne_02.mp4 --result_video checkpoints_smic/Negative_s11_ne_02_Female_Asian.mp4  --checkpoint checkpoints_smic/00000149-checkpoint.pth.tar --relative --adapt_scale
python demo.py  --config config/smic-256.yaml --source_image ../../../hdd/Data/Facial_Micro-Expression/megc2022-synthesis/target_template_face/Template_Female_Europe_crop.png  --driving_video ../../../hdd/Data/Facial_Micro-Expression/megc2022-synthesis/source_samples/Smic_challenge_256_png/Negative_s11_ne_02.mp4 --source_image_edge ../../../hdd/Data/Facial_Micro-Expression/megc2022-synthesis/target_template_face/Template_Female_Europe_crop_edge.jpg  --driving_video_edge ../../../hdd/Data/Facial_Micro-Expression/megc2022-synthesis/source_samples/Smic_challenge_256_png_edge/Negative_s11_ne_02.mp4 --result_video checkpoints_smic/Negative_s11_ne_02_Female_Europe.mp4 --checkpoint checkpoints_smic/00000149-checkpoint.pth.tar --relative --adapt_scale
python demo.py  --config config/smic-256.yaml --source_image ../../../hdd/Data/Facial_Micro-Expression/megc2022-synthesis/target_template_face/Template_Male_Asian_crop.png     --driving_video ../../../hdd/Data/Facial_Micro-Expression/megc2022-synthesis/source_samples/Smic_challenge_256_png/Negative_s11_ne_02.mp4 --source_image_edge ../../../hdd/Data/Facial_Micro-Expression/megc2022-synthesis/target_template_face/Template_Male_Asian_crop_edge.jpg     --driving_video_edge ../../../hdd/Data/Facial_Micro-Expression/megc2022-synthesis/source_samples/Smic_challenge_256_png_edge/Negative_s11_ne_02.mp4 --result_video checkpoints_smic/Negative_s11_ne_02_Male_Asian.mp4    --checkpoint checkpoints_smic/00000149-checkpoint.pth.tar --relative --adapt_scale
python demo.py  --config config/smic-256.yaml --source_image ../../../hdd/Data/Facial_Micro-Expression/megc2022-synthesis/target_template_face/Template_Male_Europe_crop.png    --driving_video ../../../hdd/Data/Facial_Micro-Expression/megc2022-synthesis/source_samples/Smic_challenge_256_png/Negative_s11_ne_02.mp4 --source_image_edge ../../../hdd/Data/Facial_Micro-Expression/megc2022-synthesis/target_template_face/Template_Male_Europe_crop_edge.jpg    --driving_video_edge ../../../hdd/Data/Facial_Micro-Expression/megc2022-synthesis/source_samples/Smic_challenge_256_png_edge/Negative_s11_ne_02.mp4 --result_video checkpoints_smic/Negative_s11_ne_02_Male_Europe.mp4   --checkpoint checkpoints_smic/00000149-checkpoint.pth.tar --relative --adapt_scale
# surprise
python demo.py  --config config/smic-256.yaml --source_image ../../../hdd/Data/Facial_Micro-Expression/megc2022-synthesis/target_template_face/Template_Female_Asian_crop.png   --driving_video ../../../hdd/Data/Facial_Micro-Expression/megc2022-synthesis/source_samples/Smic_challenge_256_png/Surprise_s20_sur_01.mp4 --source_image_edge ../../../hdd/Data/Facial_Micro-Expression/megc2022-synthesis/target_template_face/Template_Female_Europe_crop_edge.jpg  --driving_video_edge ../../../hdd/Data/Facial_Micro-Expression/megc2022-synthesis/source_samples/Smic_challenge_256_png/Surprise_s20_sur_01.mp4 --result_video checkpoints_smic/Surprise_s20_sur_01_Female_Asian.mp4   --checkpoint checkpoints_smic/00000149-checkpoint.pth.tar --relative --adapt_scale
python demo.py  --config config/smic-256.yaml --source_image ../../../hdd/Data/Facial_Micro-Expression/megc2022-synthesis/target_template_face/Template_Female_Europe_crop.png  --driving_video ../../../hdd/Data/Facial_Micro-Expression/megc2022-synthesis/source_samples/Smic_challenge_256_png/Surprise_s20_sur_01.mp4 --source_image_edge ../../../hdd/Data/Facial_Micro-Expression/megc2022-synthesis/target_template_face/Template_Female_Europe_crop_edge.jpg  --driving_video_edge ../../../hdd/Data/Facial_Micro-Expression/megc2022-synthesis/source_samples/Smic_challenge_256_png/Surprise_s20_sur_01.mp4 --result_video checkpoints_smic/Surprise_s20_sur_01_Female_Europe.mp4  --checkpoint checkpoints_smic/00000149-checkpoint.pth.tar --relative --adapt_scale
python demo.py  --config config/smic-256.yaml --source_image ../../../hdd/Data/Facial_Micro-Expression/megc2022-synthesis/target_template_face/Template_Male_Asian_crop.png     --driving_video ../../../hdd/Data/Facial_Micro-Expression/megc2022-synthesis/source_samples/Smic_challenge_256_png/Surprise_s20_sur_01.mp4 --source_image_edge ../../../hdd/Data/Facial_Micro-Expression/megc2022-synthesis/target_template_face/Template_Male_Asian_crop_edge.jpg     --driving_video_edge ../../../hdd/Data/Facial_Micro-Expression/megc2022-synthesis/source_samples/Smic_challenge_256_png/Surprise_s20_sur_01.mp4 --result_video checkpoints_smic/Surprise_s20_sur_01_Male_Asian.mp4     --checkpoint checkpoints_smic/00000149-checkpoint.pth.tar --relative --adapt_scale
python demo.py  --config config/smic-256.yaml --source_image ../../../hdd/Data/Facial_Micro-Expression/megc2022-synthesis/target_template_face/Template_Male_Europe_crop.png    --driving_video ../../../hdd/Data/Facial_Micro-Expression/megc2022-synthesis/source_samples/Smic_challenge_256_png/Surprise_s20_sur_01.mp4 --source_image_edge ../../../hdd/Data/Facial_Micro-Expression/megc2022-synthesis/target_template_face/Template_Male_Europe_crop_edge.jpg    --driving_video_edge ../../../hdd/Data/Facial_Micro-Expression/megc2022-synthesis/source_samples/Smic_challenge_256_png/Surprise_s20_sur_01.mp4 --result_video checkpoints_smic/Surprise_s20_sur_01_Male_Europe.mp4    --checkpoint checkpoints_smic/00000149-checkpoint.pth.tar --relative --adapt_scale


####################
## samm
# MEGC2022
# positive
python demo.py  --config config/samm-256.yaml --source_image ../../../hdd/Data/Facial_Micro-Expression/megc2022-synthesis/target_template_face/Template_Female_Asian_crop.png  --driving_video ../../../hdd/Data/Facial_Micro-Expression/megc2022-synthesis/source_samples/SAMM_challenge_256_png/Positive_022_3_3.mp4 --source_image_edge ../../../hdd/Data/Facial_Micro-Expression/megc2022-synthesis/target_template_face/Template_Female_Asian_crop_edge.jpg  --driving_video_edge ../../../hdd/Data/Facial_Micro-Expression/megc2022-synthesis/source_samples/SAMM_challenge_256_png_edge/Positive_022_3_3.mp4 --result_video checkpoints_samm/Positive_022_3_3_Female_Asian.mp4   --checkpoint checkpoints_casme2_smic_samm/00000149-checkpoint.pth.tar --relative --adapt_scale
python demo.py  --config config/samm-256.yaml --source_image ../../../hdd/Data/Facial_Micro-Expression/megc2022-synthesis/target_template_face/Template_Female_Europe_crop.png --driving_video ../../../hdd/Data/Facial_Micro-Expression/megc2022-synthesis/source_samples/SAMM_challenge_256_png/Positive_022_3_3.mp4 --source_image_edge ../../../hdd/Data/Facial_Micro-Expression/megc2022-synthesis/target_template_face/Template_Female_Europe_crop_edge.jpg --driving_video_edge ../../../hdd/Data/Facial_Micro-Expression/megc2022-synthesis/source_samples/SAMM_challenge_256_png_edge/Positive_022_3_3.mp4 --result_video checkpoints_samm/Positive_022_3_3_Female_Europe.mp4  --checkpoint checkpoints_casme2_smic_samm/00000149-checkpoint.pth.tar --relative --adapt_scale
python demo.py  --config config/samm-256.yaml --source_image ../../../hdd/Data/Facial_Micro-Expression/megc2022-synthesis/target_template_face/Template_Male_Asian_crop.png    --driving_video ../../../hdd/Data/Facial_Micro-Expression/megc2022-synthesis/source_samples/SAMM_challenge_256_png/Positive_022_3_3.mp4 --source_image_edge ../../../hdd/Data/Facial_Micro-Expression/megc2022-synthesis/target_template_face/Template_Male_Asian_crop_edge.jpg    --driving_video_edge ../../../hdd/Data/Facial_Micro-Expression/megc2022-synthesis/source_samples/SAMM_challenge_256_png_edge/Positive_022_3_3.mp4 --result_video checkpoints_samm/Positive_022_3_3_Male_Asian.mp4     --checkpoint checkpoints_casme2_smic_samm/00000149-checkpoint.pth.tar --relative --adapt_scale
python demo.py  --config config/samm-256.yaml --source_image ../../../hdd/Data/Facial_Micro-Expression/megc2022-synthesis/target_template_face/Template_Male_Europe_crop.png   --driving_video ../../../hdd/Data/Facial_Micro-Expression/megc2022-synthesis/source_samples/SAMM_challenge_256_png/Positive_022_3_3.mp4 --source_image_edge ../../../hdd/Data/Facial_Micro-Expression/megc2022-synthesis/target_template_face/Template_Male_Europe_crop_edge.jpg   --driving_video_edge ../../../hdd/Data/Facial_Micro-Expression/megc2022-synthesis/source_samples/SAMM_challenge_256_png_edge/Positive_022_3_3.mp4 --result_video checkpoints_samm/Positive_022_3_3_Male_Europe.mp4    --checkpoint checkpoints_casme2_smic_samm/00000149-checkpoint.pth.tar --relative --adapt_scale
# negative
python demo.py  --config config/samm-256.yaml --source_image ../../../hdd/Data/Facial_Micro-Expression/megc2022-synthesis/target_template_face/Template_Female_Asian_crop.png   --driving_video ../../../hdd/Data/Facial_Micro-Expression/megc2022-synthesis/source_samples/SAMM_challenge_256_png/Negative_018_3_1.mp4 --source_image_edge ../../../hdd/Data/Facial_Micro-Expression/megc2022-synthesis/target_template_face/Template_Female_Europe_crop_edge.jpg  --driving_video_edge ../../../hdd/Data/Facial_Micro-Expression/megc2022-synthesis/source_samples/SAMM_challenge_256_png_edge/Negative_018_3_1.mp4 --result_video checkpoints_samm/Negative_018_3_1_Female_Asian.mp4  --checkpoint checkpoints_casme2_smic_samm/00000149-checkpoint.pth.tar --relative --adapt_scale
python demo.py  --config config/samm-256.yaml --source_image ../../../hdd/Data/Facial_Micro-Expression/megc2022-synthesis/target_template_face/Template_Female_Europe_crop.png  --driving_video ../../../hdd/Data/Facial_Micro-Expression/megc2022-synthesis/source_samples/SAMM_challenge_256_png/Negative_018_3_1.mp4 --source_image_edge ../../../hdd/Data/Facial_Micro-Expression/megc2022-synthesis/target_template_face/Template_Female_Europe_crop_edge.jpg  --driving_video_edge ../../../hdd/Data/Facial_Micro-Expression/megc2022-synthesis/source_samples/SAMM_challenge_256_png_edge/Negative_018_3_1.mp4 --result_video checkpoints_samm/Negative_018_3_1_Female_Europe.mp4 --checkpoint checkpoints_casme2_smic_samm/00000149-checkpoint.pth.tar --relative --adapt_scale
python demo.py  --config config/samm-256.yaml --source_image ../../../hdd/Data/Facial_Micro-Expression/megc2022-synthesis/target_template_face/Template_Male_Asian_crop.png     --driving_video ../../../hdd/Data/Facial_Micro-Expression/megc2022-synthesis/source_samples/SAMM_challenge_256_png/Negative_018_3_1.mp4 --source_image_edge ../../../hdd/Data/Facial_Micro-Expression/megc2022-synthesis/target_template_face/Template_Male_Asian_crop_edge.jpg     --driving_video_edge ../../../hdd/Data/Facial_Micro-Expression/megc2022-synthesis/source_samples/SAMM_challenge_256_png_edge/Negative_018_3_1.mp4 --result_video checkpoints_samm/Negative_018_3_1_Male_Asian.mp4    --checkpoint checkpoints_casme2_smic_samm/00000149-checkpoint.pth.tar --relative --adapt_scale
python demo.py  --config config/samm-256.yaml --source_image ../../../hdd/Data/Facial_Micro-Expression/megc2022-synthesis/target_template_face/Template_Male_Europe_crop.png    --driving_video ../../../hdd/Data/Facial_Micro-Expression/megc2022-synthesis/source_samples/SAMM_challenge_256_png/Negative_018_3_1.mp4 --source_image_edge ../../../hdd/Data/Facial_Micro-Expression/megc2022-synthesis/target_template_face/Template_Male_Europe_crop_edge.jpg    --driving_video_edge ../../../hdd/Data/Facial_Micro-Expression/megc2022-synthesis/source_samples/SAMM_challenge_256_png_edge/Negative_018_3_1.mp4 --result_video checkpoints_samm/Negative_018_3_1_Male_Europe.mp4   --checkpoint checkpoints_casme2_smic_samm/00000149-checkpoint.pth.tar --relative --adapt_scale
# surprise
python demo.py  --config config/samm-256.yaml --source_image ../../../hdd/Data/Facial_Micro-Expression/megc2022-synthesis/target_template_face/Template_Female_Asian_crop.png   --driving_video ../../../hdd/Data/Facial_Micro-Expression/megc2022-synthesis/source_samples/SAMM_challenge_256_png/Surprise_007_7_1.mp4 --source_image_edge ../../../hdd/Data/Facial_Micro-Expression/megc2022-synthesis/target_template_face/Template_Female_Europe_crop_edge.jpg  --driving_video_edge ../../../hdd/Data/Facial_Micro-Expression/megc2022-synthesis/source_samples/SAMM_challenge_256_png_edge/Surprise_007_7_1.mp4 --result_video checkpoints_samm/Surprise_007_7_1_Female_Asian.mp4   --checkpoint checkpoints_casme2_smic_samm/00000149-checkpoint.pth.tar --relative --adapt_scale
python demo.py  --config config/samm-256.yaml --source_image ../../../hdd/Data/Facial_Micro-Expression/megc2022-synthesis/target_template_face/Template_Female_Europe_crop.png  --driving_video ../../../hdd/Data/Facial_Micro-Expression/megc2022-synthesis/source_samples/SAMM_challenge_256_png/Surprise_007_7_1.mp4 --source_image_edge ../../../hdd/Data/Facial_Micro-Expression/megc2022-synthesis/target_template_face/Template_Female_Europe_crop_edge.jpg  --driving_video_edge ../../../hdd/Data/Facial_Micro-Expression/megc2022-synthesis/source_samples/SAMM_challenge_256_png_edge/Surprise_007_7_1.mp4 --result_video checkpoints_samm/Surprise_007_7_1_Female_Europe.mp4  --checkpoint checkpoints_casme2_smic_samm/00000149-checkpoint.pth.tar --relative --adapt_scale
python demo.py  --config config/samm-256.yaml --source_image ../../../hdd/Data/Facial_Micro-Expression/megc2022-synthesis/target_template_face/Template_Male_Asian_crop.png     --driving_video ../../../hdd/Data/Facial_Micro-Expression/megc2022-synthesis/source_samples/SAMM_challenge_256_png/Surprise_007_7_1.mp4 --source_image_edge ../../../hdd/Data/Facial_Micro-Expression/megc2022-synthesis/target_template_face/Template_Male_Asian_crop_edge.jpg     --driving_video_edge ../../../hdd/Data/Facial_Micro-Expression/megc2022-synthesis/source_samples/SAMM_challenge_256_png_edge/Surprise_007_7_1.mp4 --result_video checkpoints_samm/Surprise_007_7_1_Male_Asian.mp4     --checkpoint checkpoints_casme2_smic_samm/00000149-checkpoint.pth.tar --relative --adapt_scale
python demo.py  --config config/samm-256.yaml --source_image ../../../hdd/Data/Facial_Micro-Expression/megc2022-synthesis/target_template_face/Template_Male_Europe_crop.png    --driving_video ../../../hdd/Data/Facial_Micro-Expression/megc2022-synthesis/source_samples/SAMM_challenge_256_png/Surprise_007_7_1.mp4 --source_image_edge ../../../hdd/Data/Facial_Micro-Expression/megc2022-synthesis/target_template_face/Template_Male_Europe_crop_edge.jpg    --driving_video_edge ../../../hdd/Data/Facial_Micro-Expression/megc2022-synthesis/source_samples/SAMM_challenge_256_png_edge/Surprise_007_7_1.mp4 --result_video checkpoints_samm/Surprise_007_7_1_Male_Europe.mp4    --checkpoint checkpoints_casme2_smic_samm/00000149-checkpoint.pth.tar --relative --adapt_scale

